apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-a
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-a
    spec:
      containers:
      - image: public.ecr.aws/e0f5p9d7/cloudcampla/observability-demo-app:latest
        imagePullPolicy: Always
        name: app-a
        ports:
        - containerPort: 8080
        env:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://tempo.observability
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: http/protobuf
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.name=app-a,app=app-a
          - name: MANAGEMENT_METRICS_TAGS_APPLICATION
            value: app-a
          - name: OTEL_METRICS_EXPORTER
            value: none