apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: config-keda
  namespace: keda
  files:
  - values.yaml=config-keda.yaml
  options:
    disableNameSuffixHash: true
resources:
  - namespace.yaml
  - helm-repositories.yaml
  - helm-releases.yaml