apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: config-ingress-nginx
  namespace: ingress-nginx
  files:
  - values.yaml=config-ingress-nginx.yaml
  options:
    disableNameSuffixHash: true
- name: nginx-configuration
  namespace: ingress-nginx
  literals:
  - enable-vts-status="true"
  options:
    disableNameSuffixHash: true
resources: 
  - namespace.yaml
  - helm-repositories.yaml
  - helm-releases.yaml