apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: observability
spec:
  interval: 1m
  chart:
    spec:
      chart: tempo
      version: "1.1.0" 
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values: 
    replicas: 2
    tempo:
      search:
        enabled: true
      multitenancyEnabled: false
      reportingEnabled: true
      metricsGenerator:
        enabled: true
        remoteWriteUrl: "http://prometheus-kube-prometheus-prometheus:9090/api/v1/write"
      retention: 24h
      global_overrides:
        per_tenant_override_config: /conf/overrides.yaml
      overrides: {}
      server:
        http_listen_port: 3100
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
          wal:
            path: /var/tempo/wal
      receivers:
        jaeger:
          protocols:
            grpc:
              endpoint: 0.0.0.0:14250
            thrift_binary:
              endpoint: 0.0.0.0:6832
            thrift_compact:
              endpoint: 0.0.0.0:6831
            thrift_http:
              endpoint: 0.0.0.0:14268
        opencensus:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"
    tempoQuery:
      enabled: true
      service:
        port: 16686
    service:
      type: ClusterIP
    persistence:
      enabled: true
      storageClassName: ebs-sc
      accessModes:
        - ReadWriteOnce
      size: 50Gi
    serviceAccount:
      create: true
---