apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  interval: 1m
  chart:
    spec:
      chart: karpenter
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-system
      version: 'v0.31.0'
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    serviceAccount:
      annotations:
        "eks.amazonaws.com/role-arn": "arn:aws:iam::628924030472:role/agosto-eks-cluster-karpenter-role"
    settings:
      aws:
        defaultInstanceProfile: "KarpenterNodeInstanceProfile-agosto-eks-cluster"
        clusterName: "agosto-eks-cluster"
        clusterEndpoint: "https://399F015AF4F81A58C95F869667EF49CB.gr7.us-east-1.eks.amazonaws.com"
        interruptionQueueName: "agosto-eks-cluster"
    controller:
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "1Gi"
